/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioDevice {
  id: string
  name: string
  state: number
  isDefault: boolean
}
export declare function getAllOutputDevices(): Array<AudioDevice>
export declare function getDefaultOutputDevice(): AudioDevice | null
export declare class AudioMonitor {
  constructor()
  setDevice(deviceId?: string): void
  start(chunkSize?: number): void
  stop(): void
  getSpectrum(numBands: number): Array<number>
  get currentDeviceId(): string | null
  get running(): boolean
  get chunkSize(): number
}
