/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioDevice {
  id: string
  name: string
  sampleRate: number
  bufferSize?: number
  isDefault: boolean
}
export declare function getAllOutputDevices(): Array<AudioDevice>
export declare function getDefaultOutputDevice(): AudioDevice | null
export declare class AudioMonitor {
  constructor()
  setDevice(id: string): void
  play(): void
  pause(): void
  getSpectrum(bands?: number, decay?: number, size?: number): Array<number>
}
